### ISSUE TITLE
Arduino battery monitor example fails to compile ...

### ISSUE THREAD

**Issue by RandoSY** [strid3r21/BeeS3#1]
Hello!

There defs for "RGB_PWR" and "RGB_DATA" where missing in the Arduino battery monitor example.  I took a look at the schematic but could not get the naming conventions for those specific PINS figured out. 

Suggestions?

**Comment by RandoSY** [comment]
I did some poking around the ESP32 IDF, and found some info on correctly defining GPIO pins... (driver/gpio.h ?) 

GPIO_NUM_XX seems to be correct. 

#define RGB_PWR GPIO_NUM_34

#define RGB_DATA GPIO_NUM_40

I guess those pin numbers are OK, the schematic was kinda of ambiguous. I don't have a test board yet to work with.

`Successfully created esp32s3 image.
"C:\\Users\\randa\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.4/tools/gen_esp32part.exe" -q "C:\\Users\\randa\\AppData\\Local\\Temp\\arduino_build_909812/partitions.csv" "C:\\Users\\randa\\AppData\\Local\\Temp\\arduino_build_909812/Battery.ino.partitions.bin"
Using library BeeS3-Arduino-Helper-main at version 1.0.7 in folder: C:\Users\randa\Documents\Arduino\libraries\BeeS3-Arduino-Helper-main 
"C:\\Users\\randa\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\xtensa-esp32s3-elf-gcc\\gcc8_4_0-esp-2021r2-patch3/bin/xtensa-esp32s3-elf-size" -A "C:\\Users\\randa\\AppData\\Local\\Temp\\arduino_build_909812/Battery.ino.elf"
Sketch uses 255057 bytes (19%) of program storage space. Maximum is 1310720 bytes.
Global variables use 13912 bytes (4%) of dynamic memory, leaving 313768 bytes for local variables. Maximum is 327680 bytes.
`

**Comment by RandoSY** [comment]
I ordered a board, will check when it arrives ... 
:)

**Comment by strid3r21** [comment]
hi! thanks for ordering a board! since you closed this issue i take it to mean you were able to compile the battery example in the ESP-IDF? 

i haven't messed with the IDF with this board to program it as most people use arduino, micro-python and circuit-python. but ill happily help you out in any way i can to help sort out any issues you may run into with ESP-IDF. it should be pretty straight forward tho.

here is a list of all the pins and their associated definitions

`
static const uint8_t TX = 43;
static const uint8_t RX = 44;

static const uint8_t SDA = 37;
static const uint8_t SCL = 36;

static const uint8_t SS    = 5;
static const uint8_t MOSI  = 35;
static const uint8_t MISO  = 38;
static const uint8_t SDO  = 35;
static const uint8_t SDI  = 38;
static const uint8_t SCK   = 39;

static const uint8_t A3 = 3;
static const uint8_t A4 = 4;
static const uint8_t A5 = 5;
static const uint8_t A6 = 6;
static const uint8_t A7 = 7;
static const uint8_t A8 = 8;
static const uint8_t A9 = 9;
static const uint8_t A10 = 10;

static const uint8_t D3 = 3;
static const uint8_t D4 = 4;
static const uint8_t D5 = 5;
static const uint8_t D6 = 6;
static const uint8_t D7 = 7;
static const uint8_t D8 = 8;
static const uint8_t D9 = 9;
static const uint8_t D10 = 10;
static const uint8_t D35 = 35;
static const uint8_t D36 = 36;
static const uint8_t D37 = 37;
static const uint8_t D38 = 38;
static const uint8_t D39 = 39;
static const uint8_t D43 = 43;
static const uint8_t D44 = 44;

static const uint8_t T3 = 3;
static const uint8_t T4 = 4;
static const uint8_t T5 = 5;
static const uint8_t T6 = 6;
static const uint8_t T7 = 7;
static const uint8_t T8 = 8;
static const uint8_t T9 = 9;
static const uint8_t T10 = 10;

static const uint8_t VBAT_VOLTAGE = 1;
static const uint8_t RGB_DATA = 48;
static const uint8_t RGB_PWR = 34;`

**Comment by RandoSY** [comment]
Hi,

Thanks for the info.

I'm using Arduino as well.  My issue was that these two VARS did not had a value that the compiler could understand.

#define RGB_PWR GPIO_NUM_34

#define RGB_DATA GPIO_NUM_40

That is, RBG_PWR and RGB_DATA did not resolve to a value that the IDF tool-chain could understand.  The Arduino IDE resolves it's compilation in terms of the ESP-IDF, as the Arduino IDE relies on its resources to produce and executable binary file.  One great thing about Espressif is they really respect Arduino as a platform, and work hard to make everything work correctly. 

I used the schematic to try and resolve what pin numbers should be used, and the information form the gpio.h file, on what exact naming conventions to use to call them correctly.  Once I get my board I can check to see if I'm thinking about this correctly.
